quarkus.datasource.db-kind = mysql
quarkus.datasource.username = root
quarkus.datasource.password = Mayo010507!
quarkus.datasource.jdbc.url = jdbc:mysql://localhost:3306/ecommerce

quarkus.resteasy.path=/api/v1

firebase.api.key=AIzaSyBRRWKNyNw_spg1sEiYFwxM3a2PgEusH04

#quarkus.hibernate-orm.database.generation = drop-and-create